HUNGR_WebApplication/HUNGR.WebApp/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HUNGR.WebApp.Data;
using HUNGR.WebApp.Models;
using HUNGR.WebApp.ViewModels;

namespace HUNGR.WebApp.Controllers
{
    public class EventsController : Controller
    {
        private readonly HUNGRDbContext dbContext;

        public EventsController(HUNGRDbContext context)
        {
            dbContext = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            return View(await dbContext.Events.ToListAsync());
        }


        // GET: Events/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = $"The Event with Id = {id} cannot be found";
                return View("NotFound");
                //return NotFound();
            }

            var thisEvent = await dbContext.Events
                .FirstOrDefaultAsync(m => m.Id == id);
            if (thisEvent == null)
            {
                ViewBag.ErrorMessage = $"The Event with Id = {id} cannot be found";
                return View("NotFound");
            }
            List<EventParticipant> eventParticipants = dbContext.EventParticipants.Where(ep => ep.EventId == id).ToList();
            List<FoodTruck> eventTrucks = new List<FoodTruck>();

            foreach( var ep in eventParticipants)
            {
                var truckId = ep.FoodTruck;
                FoodTruck foodTruck = dbContext.FoodTrucks.FirstOrDefault(ft => ft.FoodTruckId == ep.FoodTruckId);
                eventTrucks.Add(foodTruck);
            }
            EventDetailsViewModel model = new EventDetailsViewModel()
            {
                EventDetails = thisEvent,
                EventFoodTrucks = eventTrucks
            };

            return View(model);
        }
    }
}

HUNGR_WebApplication/HUNGR.WebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HUNGR.WebApp.Data;
using HUNGR.WebApp.Models;
using HUNGR.WebApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static HUNGR.WebApp.Models.FoodEnum;
using System.Security.Claims;

namespace HUNGR.WebApp.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly HUNGRDbContext dbContext;

        public UserController(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, HUNGRDbContext context)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            dbContext = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UserProfile(string userId)
        {
            var id = userId;
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }

            var reviews = dbContext.Reviews.Where(r => r.UserId == userId).ToList();

            var favTrucksId = dbContext.UserFavouriteTrucks.Where(ft => ft.Id == userId).ToList();
            var listOfFoodTrucks = new List<FoodTruck>();
            
            foreach(var truckId in favTrucksId)
            {
                var foodTruck = await dbContext.FoodTrucks
                .FirstOrDefaultAsync(m => m.FoodTruckId == truckId.FoodTruckId);

                listOfFoodTrucks.Add(foodTruck);
            }

            var model = new UserProfileViewModel
            {
                UserId = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                FoodCat = (FoodEnum.FoodCat)user.FoodCategory,
                City = user.City,
                Province = user.Province,
                ProfileImagePath = user.ProfileImage,
                Reviews = reviews,
                FavouriteTrucks = listOfFoodTrucks
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MyProfile()
        {

            //Get Basic User Info
            //var uId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier); 
            ApplicationUser UserProfile = await userManager.FindByIdAsync(userId);
            var UsersReviews = dbContext.Reviews.Where( r=> r.UserId == UserProfile.Id && r.FoodTruckId != null).ToList();
            List<UserFavouriteTruck> favTruckData = dbContext.UserFavouriteTrucks.Where(favT => favT.Id == UserProfile.Id).ToList();

            var listOfFoodTrucks = new List<FoodTruck>();

            foreach (var truckId in favTruckData)
            {
                var favFoodTruck = await dbContext.FoodTrucks
                .FirstOrDefaultAsync(m => m.FoodTruckId == truckId.FoodTruckId);

                listOfFoodTrucks.Add(favFoodTruck);
            }

            FoodTruck foodTruck = await dbContext.FoodTrucks
                .Include(f => f.ApplicationUser)
                .Include(f => f.FoodCategory)
                .Include(f => f.Reviews)
                .Include(f => f.UserFavouriteTrucks)
                .FirstOrDefaultAsync(m => m.FoodTruckId == UserProfile.Id);

            var model = new MyProfileViewModel
            {
                User = UserProfile,
                UserReviews = UsersReviews,
                FavouriteTrucks = listOfFoodTrucks
            };

            if(foodTruck == null)
            {
                return View(model);
            }
            model.User.FoodTruck = foodTruck;

            return View(model);
        }
    }
}

HUNGR_WebApplication/HUNGR.WebApp/Views/Shared/NotFound.cshtml
@{ 
    ViewBag.Title = "Not Found"; 
}
<h1>@ViewBag.ErrorMessage</h1>
<a asp-action="index" asp-controller="home">Click Here To Navigate To The Home Page</a>

HUNGR_WebApplication/HUNGR.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationSerivce
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HUNGR.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <script type='text/javascript'
            src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=AodJbksXSBCydQxBDZ4_ooFRGs8FrNserUXrYIj0FXBHYKm4eEF-BNgybscQFYOH'
            async defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    



</head>
<body>
    <div class="jumbotron text-center bg-danger mb-0">
        @if (User.IsInRole("Admin"))
        {
            <div class="display-1 2rem font-weight-bolder text-center "><a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">ADMIN</a></div>
            <div class="h4 text-white">Ultimate Food Trucks Power</div>
        }
        else if (User.IsInRole("FoodTruck"))
        {
            <div class="display-1 2rem font-weight-bolder text-center "><a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">HUNGR OWNERS</a></div>
            <div class="h4 text-white">Managing Your Favourite Food Trucks</div>
        }
        else
        {
            <div class="display-1 2rem font-weight-bolder text-center "><a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">HUNGR</a></div>
            <div class="h4 text-white">Finding Your Favourite Food Trucks</div>
        }
        <div class="col-lg-1 offset-lg-1 text-light">
        </div>

    </div>
    <header class="">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger mb-3 ">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HUNGR</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1 justify-content-around">

                        <li class="nav-item h3">
                            <a class="nav-link text-white" asp-area="" asp-controller="FoodTrucks" asp-action="Index">Food Trucks</a>
                        </li>
                        <li class="nav-item h3">
                            <a class="nav-link text-white" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item h3">
                                <a class="nav-link text-white" asp-area="" asp-controller="Administration" asp-action="CreateEvent">Admin Events</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item h3">
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="MyProfile">Profile</a>
                            </li>
                        }
                        @*@if ((await authorizationSerivce.AuthorizeAsync(User, "UserPolicy")).Succeeded)
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Foodtrucks" asp-action="Create">Create Your Food Truck!</a>
                            </li>
                            }*@
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        


        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HUNGR.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="_framework/blazor.server.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

    <script src="~/lib/jquery-ui/jquery-ui.js"></script>

    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: true)

    }


</body>
</html>